### ISSUE TITLE
Multi-Term - Invalid Face: Unspecified

### ISSUE THREAD

**Issue by bashhack** [hlissner/emacs-doom-theme#54]
As of the refactor changes, I'm now seeing Multi-Term instances register the following message:

"error in process filter: Invalid face: unspecified"

**Comment by hlissner** [comment]
Odd. I could only reproduce this with pre-refactor emacs-doom-theme. 

I believe the problem is that `ansi-term-color-vector` has somehow been set to a vector of faces that don't exist, or has an invalid face among them.

Please do the following:

1. After you've tried to run `multi-term`, inspect the value of `ansi-term-color-vector` (`M-x describe-variable RET ansi-term-color-vector`), and let me know what it contains.
2. Tell me what version of Emacs you're running, and on what OS.

The default value *should* be `[term term-color-black term-color-red term-color-green term-color-yellow term-color-blue term-color-magenta term-color-cyan term-color-white]`. If this is not the case, either a) something in your config modifying it, b) your version of Emacs has a different default for `ansi-term-color-vector` or c) I've broken the universe.

**Comment by bashhack** [comment]
Thanks for the quick reply!

I'm currently running 25.1.1 on Ubuntu 16.04.

After inspecting `ansi-term-color-vector`, the following is returned:

`ansi-term-color-vector is a variable defined in ‘term.el’.
Its value is
[unspecified "#1B2229" "#ff6c6b" "#98be65" "#ECBE7B" "#51afef" "#c678dd" "#46D9FF" "#DFDFDF"]`

**Comment by hlissner** [comment]
Huh, even weirder. Those are the old settings (pre-refactor).

If you'd like a quick solution to the problem, this will fix your issue:

```emacs-lisp
(setq ansi-term-color-vector [term term-color-black term-color-red term-color-green term-color-yellow term-color-blue term-color-magenta term-color-cyan term-color-white])
```

If you do have time, I'd appreciate it if you could try:

1. Uninstalling and reinstalling doom-themes (`M-x package-reinstall RET doom-themes`), and restart Emacs for good measure.
2. If that doesn't work: `M-x find-function RET doom-common-variables`, scroll to the bottom and look for a `ansi-term-color-vector` definition (it'll be the last one). It'll be underneath `ansi-color-names-vector` (careful not to mistake the two). 

    If it's there you have the old version of doom-themes for some reason (perhaps MELPA hasn't gotten around to building the updated version yet). Only solution here is to use my solution above for now and wait a couple hours.
3. See if you have a `custom-set-variables` line in your init.el, see if a setting for `ansi-term-color-vector` has snuck in there somehow. If so, delete it and you'll be golden.

If none of those work, then there are some Cthulhu-level shenanigans afoot.

**Comment by bashhack** [comment]
It definitely seems to have been a MELPA package propagation issue, as pulling again late yesterday evening ended up finally resolving the issue entirely! Wonderful!

Thanks again for such a great package and have an awesome week!

**Comment by vityafx** [comment]
Commenting out the `ansi-term-color-vector` helped me to solve this problem.

**Comment by hlissner** [comment]
@vityafx you're still experiencing this 2 year old issue? Could you try reinstalling the plugin?

**Comment by vityafx** [comment]
Yes, and it has happened on freshly-installed emacs 26.2 (spacemacs) with config file from another machine. I have commented it out and everything went fine after.

**Comment by hlissner** [comment]
@vityafx What doom theme are you using? And are you using terminal or GUI Emacs?

**Comment by vityafx** [comment]
I was using GUI emacs and `doom-spacegrey` when it happened.

**Comment by hlissner** [comment]
If possible, could you try `M-x eval-expression RET (vconcat (mapcar #'doom-color '(bg red green yellow blue magenta cyan fg)))` and tell me what that returns?

I suspect this error occurs because one (or more) of the values in `ansi-color-names-vector` is `nil` _or_ the vector isn't exactly 8 elements long (for some reason).

I can't reproduce this on 26.2 with Doom and vanilla Emacs, running the following:

```elisp
(require 'doom-themes)
(load-theme 'doom-spacegrey t)
(require 'ansi-color)
(message "-- %s" ansi-color-names-vector)
```

So if `ansi-color-names-vector` is as I suspect, then Spacemacs may be doing something else to it.

**Comment by vityafx** [comment]
I have already got rid of this variable. I could try to return it back and test it, but only next Monday.

**Comment by vityafx** [comment]
Am I right that I should return the variable back where it was declared in my `.spacemacs` file before the return value of the expression you wrote, the one with colors?
